### PR TITLE
Use a higher font weight & a darker color for body text

### LINKED ISSUE #1: Body text is difficult to read
While I really like this theme, I've found the text *very* difficult to read. I know that legibility/readability is a subjective thing, but I'm finding myself straining and leaning forward in my chair so that I can actually see the text. 

Here's two screen shots that show the text being difficult to read - for me, at least, on the couple monitors I have available to view it on - in Chrome:

[OSX](http://f.cl.ly/items/0P2X3J3v1F301f0K313z/Screen%20Shot%202012-04-06%20at%2011.37.53%20PM.png)
[Windows 7](http://i.imgur.com/gxj08.png)

### PR DESCRIPTION
**Pull request by thomasboyt**
Fixes #1.

### CODE REVIEW

**Comment by mef** [comment]
+1

**Comment by vially** [comment]
:+1:

**Comment by r04r** [comment]
:+1:

**Comment by kgaughan** [comment]
:+1:

**Comment by hfuller** [comment]
Yes, please incoropriate, it is quite hard to read this theme.
Thankfully, tools such as Readability exist. But ideally I wouldn't need them.

**Comment by beatgammit** [comment]
:+1:

**Comment by neuhaus** [comment]
This theme is being used on quite a few sites I visit, and it always gets my attention in a negative sense because it's hard to read!
Also, since it's one of github's default themes, some people are reluctant to change their copy to make it more readable.

Here is what it looks like (approximately) in real life on my monitor (without the moire of course)

hard_to_read

**Pull request merged**
